///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MovieDescription {
/*
{
  "id": 2,
  "title": "The Godfather",
  "description": "1972 American crime film directed by Francis Ford Coppola, who co-wrote the screenplay with Mario Puzo, based on Puzo's best-selling 1969 novel of the same name.",
  "rating": "4/5",
  "posterPictureUrl": "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg"
} 
*/

  int? id;
  String? title;
  String? description;
  String? rating;
  String? posterPictureUrl;

  MovieDescription({
    this.id,
    this.title,
    this.description,
    this.rating,
    this.posterPictureUrl,
  });
  MovieDescription.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    rating = json['rating']?.toString();
    posterPictureUrl = json['posterPictureUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['rating'] = rating;
    data['posterPictureUrl'] = posterPictureUrl;
    return data;
  }
}
