///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MovieListData {
/*
{
  "id": 1,
  "title": "The Shawshank Redemption",
  "shortDescription": "1994 American prison drama film written and direct",
  "tilePictureUrl": "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg"
} 
*/

  int? id;
  String? title;
  String? shortDescription;
  String? tilePictureUrl;

  MovieListData({
    this.id,
    this.title,
    this.shortDescription,
    this.tilePictureUrl,
  });
  MovieListData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    shortDescription = json['shortDescription']?.toString();
    tilePictureUrl = json['tilePictureUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['shortDescription'] = shortDescription;
    data['tilePictureUrl'] = tilePictureUrl;
    return data;
  }
}

class MovieList {
/*
{
  "data": [
    {
      "id": 1,
      "title": "The Shawshank Redemption",
      "shortDescription": "1994 American prison drama film written and direct",
      "tilePictureUrl": "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg"
    }
  ]
} 
*/

  List<MovieListData?>? data;

  MovieList({
    this.data,
  });
  MovieList.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MovieListData>[];
      v.forEach((v) {
        arr0.add(MovieListData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
